### ISSUE TITLE
[BE] 회원가입 API 구현

### ISSUE THREAD

**Issue by jun108059** [programmers-kdt-full-stack-3rd/todo-goal-tracker#1]
## ✍🏻 Description

사용자의 새로운 계정을 생성하는 API를 구현합니다.

## ✅ To-Do

- [ ] POST /api/register 엔드포인트 생성
- [ ] 요청 바디 유효성 검사
- [ ] 비밀번호 해싱 처리
- [ ] 사용자 정보 데이터베이스에 저장
- [ ] JWT 토큰 생성 및 응답

## 📨 ETC

FE 개발 task와 연계합니다.
