### ISSUE TITLE
[BE] 카테고리 생성 API 구현

### ISSUE THREAD

**Issue by jun108059** [programmers-kdt-full-stack-3rd/todo-goal-tracker#3]
## ✍🏻 Description

목표 설정을 위한 카테고리 생성 API를 구현합니다.

## ✅ To-Do

- [ ] POST /api/categories 엔드포인트 생성
- [ ] 요청 바디 유효성 검사
- [ ] 카테고리 정보 데이터베이스에 저장
